### ISSUE TITLE
Travis is giving false positives

### ISSUE THREAD

**Issue by raldridge11** [raldridge11/XSteamPython#163]
Review of logs give errors for tests that aren't getting picked up.

Example:
```bash
======================================================================
ERROR: test_Psat_T (Psat_Tests.Test_Psat_T)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/raldridge11/XSteamPython/tests/Psat_Tests.py", line 23, in test_Psat_T
    temperature, PsatCompare = Data.getOneDimensionalTestData('SIUnits_Psat_T.npz')
  File "/home/travis/build/raldridge11/XSteamPython/tests/Data.py", line 13, in getOneDimensionalTestData
    data = np.load(npzfile)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: 'SIUnits_Psat_T.npz'
```
Cannot find the test data.

**Comment by raldridge11** [comment]
Proposing an optional `-d` option for the test runner that the user can set to point to test data. Will default to current working directory.

**Comment by raldridge11** [comment]
Logs as of build 104 show that the tests are actually passing.
